language: python
python:
  - "3.6"
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

install:
  - pip install black==19.3b0
  - yarn
  - yarn build

script:
  - docker-compose run test
  - "black --check --diff budgetportal manage.py discourse --exclude 'budgetportal/(bulk_upload|signals).py'"
