language: python
python:
  - "3.6"
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

install:
  - pip install black==19.10b0
  - yarn
  - yarn build

script:
  - docker-compose run test
  - "black --check --diff budgetportal manage.py discourse --exclude 'budgetportal/(bulk_upload|signals).py'"

after_script:
  # Log output in case issues occurred where this can help us debug quicly
  - docker-compose logs db elasticsearch

  # Run codecov passing appropriate codecov.io CI environment variables to container
  - "docker-compose run --rm `bash <(curl -s https://codecov.io/env)` test codecov"
