version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=budgetportal
      - POSTGRES_DB=budgetportal
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python manage.py runserver_plus --nopin 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgresql://budgetportal@db/budgetportal
      - DJANGO_DEBUG_TOOLBAR=${DJANGO_DEBUG_TOOLBAR}
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=budgetportal-storage
      - AWS_S3_ENDPOINT_URL=http://minio:9000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: tox
    environment:
      - DATABASE_URL=postgresql://budgetportal@db/budgetportal_test
    volumes:
      - .:/code
    depends_on:
      - db

  minio:
    image: "minio/minio:RELEASE.2019-10-12T01-39-57Z"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    command: minio --compat server data

volumes:
  db-data:
  minio-data:
