name: Budget portal

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        
    - uses: actions/setup-node@v2
      with:
        node-version: "13.14.0"
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==19.10b0
        npm install -g yarn@1.21.1
        yarn
        yarn build
    - name: Docker image
      run: |
        docker-compose run --rm test python manage.py collectstatic --no-input
        docker-compose run --rm test
        black --check --diff budgetportal manage.py discourse
      
    - name: Logging and code quality
      run: |
        docker-compose logs db solr minio
        docker-compose run --rm `bash <(curl -s https://codecov.io/env)` test codecov

